### ISSUE TITLE
Analysis Branch?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/osprey#74]
What's the story with the analysis branch (https://github.com/mpharrigan/osprey/tree/analysis)?  Is this something that's ready for consumption?

**Comment by kyleabeauchamp** [comment]
I suppose I answered my own question:

```
    def results_as_dataframe(config, *, project_name=None, project_name_filter=None,
                                      ^
SyntaxError: invalid syntax
```

**Comment by rmcgibbo** [comment]
I don't know what the status of @mpharrigan's branch is, but that syntax error is just because you're using py2 on py3-only source.

**Comment by kyleabeauchamp** [comment]
The branch seemed to have the code I needed, e.g. getting stuff from db into pandas:

```
import osprey.config, osprey.trials
import pandas as pd

config = osprey.config.Config("./config.yaml")

session = config.trials()
items = [cursor.to_dict() for cursor in session.query(osprey.trials.Trial).all()]
df = pd.DataFrame(items).set_index('id')

df.mean_test_score.plot()
```

**Comment by rmcgibbo** [comment]
I had just been using `$ osprey dump` to get a json file, and then loading the json with pandas. But +1 to adding more tools.

**Comment by mpharrigan** [comment]
I wrote that code because I was doing a lot of copy-pasting in IPython, but I don't know exactly how generaly applicable it is.

And yes, keyword only arguments :star:
