### ISSUE TITLE
bokeh is broken

### ISSUE THREAD

**Issue by kyleabeauchamp** [pandegroup/osprey#80]
1.  Need to replace `from bokeh.objects import HoverTool, ColumnDataSource` with `from bokeh.models import HoverTool, ColumnDataSource`  (as of Nov. 2014)
2.  `bk.hold()` and that style of plotting has been deprecated (https://github.com/bokeh/bokeh/blob/7af50c4dc2dd9c2335a7a8a7855a4bb2f90bc6d2/sphinx/source/docs/releases/0.7.0.rst)
3.  The API is so unstable that I suspect we should stay away.

**Comment by kyleabeauchamp** [comment]
(1) is an easy enough fix (https://github.com/pandegroup/osprey/blob/master/osprey/execute_plot.py#L15) but (2) requires more cycles than I have

**Comment by cxhernandez** [comment]
https://github.com/pandegroup/osprey/pull/85
